### ISSUE TITLE
SpliceFitPareto() with EVTtruncation = TRUE can lead to NaN value for upper truncation point

### ISSUE THREAD

**Issue by RoelVerbelen** [TReynkens/ReIns#3]
Hey @TReynkens, 

I've noticed in practice that some data sets and splicing point settings can lead to an invalid estimate of the upper truncation point for the spliced mixed Erlang and truncated Pareto distribution. 

Here demonstrated with some generated data:

``` r
library(ReIns)

# Pareto random sample
set.seed(123)
X <- rpareto(500, shape = 2)

# Splice ME and Pareto
splicefit <- SpliceFitPareto(X, const = 0.9, EVTtruncation = TRUE, M = 5, s = 1)
#> Error in if (endpoint <= scale) {: missing value where TRUE/FALSE needed
```

<sup>Created on 2023-11-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by TReynkens** [comment]
Hi @RoelVerbelen,

Thanks for the notification. The bug is fixed in [8b302e9](https://github.com/TReynkens/ReIns/commit/8b302e9bb0811576386d15b2e1a897e1d7b821d2). It happens that the truncated Hill estimator gives Infinity as estimate for the endpoint. In this case, the code now fits an untruncated instead of a truncated Pareto distribution.

**Comment by RoelVerbelen** [comment]
Great, thanks @TReynkens!

Could the code possibly generate a warning message to signal this unexpected behavior of returning an untruncated Pareto tail when a truncated one is requested?

**Comment by TReynkens** [comment]
Added in https://github.com/TReynkens/ReIns/commit/7ee5b30c6c5eafc81d299115cf6e07dc89ed65bd. New version is on its way to CRAN.
